version: "3.9"

services:
  lorita-bot-backend:
    image: lorita-bot-backend
    restart: unless-stopped
    environment:
      - LORITA_BOT_BACKEND_PORT=9999
      - LORITA_BOT_BACKEND_DEBUG=True
      - LORITA_BOT_BACKEND_BASEURL=/api/v1
      - LORITA_BOT_BACKEND_LOG_LEVEL=DEBUG
      - LORITA_BOT_BACKEND_TWILIO_ACCOUNT_SID=******
      - LORITA_BOT_BACKEND_TWILIO_AUTH_TOKEN=*****
      - LORITA_BOT_BACKEND_DG_KEY=*****
    ports:
      - 9999:9999
    healthcheck:
      test: curl --fail http://0.0.0.0:9999 || exit 1
      interval: 10s
      timeout: 10s
      start_period: 10s
      retries: 3

  lorita-bot-frontend:
    image: lorita-bot-frontend
    restart: unless-stopped
    environment:
      - LORITA_BOT_FRONTEND_PORT=3000
      - LORITA_BOT_BACKEND_PORT=9999
      - LORITA_BOT_BACKEND_BASE_URL=lorita-bot-backend
    ports:
      - 3000:3000