version: "3.9"

services:
  lorita-bot-backend:
    container_name: lorita-bot-backend
    image: lorita-bot-backend:latest
    build:
      context: .
      dockerfile: backend/Dockerfile
    env_file:
      - backend/.env
