import Head from 'next/head'
import Image from 'next/image'
import Button from '../components/Button'
import {Telegram, WhatsApp} from "../components/Icons"
import styles from '../styles/Home.module.css'


export default function Home() {
  const handleWhatsappClick = () => {
    window.open("https://wa.me/14155238886?text=join%20government-number");
  }

  const handleTelegramClick = () => {
    window.open("https://t.me/lorita_rita_bot");
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Lorita Bot 🦜</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png" />
        <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png" />
        <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png" />
        <link rel="manifest" href="/site.webmanifest" />
      </Head>

      <main className={styles.main}>
        <section className={styles.section}>
          <Image src="/lorita-bot-logo.png" alt="logo" width={120} height={120}/>
          <h1 className={styles.title}>
            Lorita Bot
          </h1>
          <h2 className={styles.subtitle}> Lorita helps you to transcript audio messages of your chat app</h2>
          
          <div>
            <Button onClick={handleTelegramClick} color={"telegram"} >
              <Telegram className={styles.telegram} />
              Start with Telegram
            </Button>
          </div>

          <div>
            <Button onClick={handleWhatsappClick}  color={'whatsapp'} >
              <WhatsApp className={styles.whatsapp} />
              Start with WhatsApp
            </Button>
          </div>
        </section>
      </main>
    </div>
  )
}
