name: Publish Frontend Docker Image

on: [ push ]

jobs:
  publish-lorita-bot-frontend-image:
    runs-on: ubuntu-latest
    steps:
      # Get the repository's code
      - name: Checkout
        uses: actions/checkout@v2

      # https://github.com/docker/setup-qemu-action
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      # https://github.com/docker/setup-buildx-action
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: latest

      - name: Docker meta
        id: meta # you'll use this in the next step
        uses: docker/metadata-action@v3
        with:
          # list of Docker images to use as base name for tags
          images: |
            ghcr.io/olidroide/lorita-bot
          # Docker tags based on the following events/attributes
          tags: |
            type=raw,value=frontend-latest
          labels: |
            org.opencontainers.image.title=lorita-bot-frontend
            org.opencontainers.image.description=Speech to text for chats apps
            org.opencontainers.image.vendor=olidroide

      - name: Login to GHCR
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

#      - name: Build image
#        uses: docker/bake-action@v1
#        with:
#          files: |
#            ./docker-bake.hcl
#            ${{ steps.meta.outputs.bake-file }}
#          targets: lorita-bot-backend-release
#          pull: false
#          push: ${{ github.event_name != 'pull_request' }}
#

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: frontend/Dockerfile
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
