name: Tests
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      LORITA_BOT_BACKEND_TESTING: True
    strategy:
      matrix:
        python-version: [3.9]

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python all python version
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements.txt
          pip install -r backend/requirements.test.txt
          pip install -e backend

      - name: Run Tests
        run: PYTHONPATH=$(pwd)/backend/src python -m pytest backend/tests -vvv